### ISSUE TITLE
Access ODBC queries with [ODBC;...].table references fail under pyodbc but work elsewhere (VBScript, .NET)

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#192]
The Microsoft Access Database Engine allows us to include tables from an external database by prefixing the table name with the database location. If the database location is an ODBC data source the prefix is of the form

```sql
SELECT ... FROM [ODBC;DSN=mydsn].tablename
```

or

```sql
SELECT ... FROM [ODBC;DRIVER=...;SERVER=...;...].tablename
```

Testing shows that such queries work when called via Access ODBC from VBScript and .NET, but fail when called via Access ODBC using pyodbc.

Working VBScript code:

```vbs
Option Explicit
Dim conn_str_sql
conn_str_sql = "DRIVER=ODBC Driver 11 for SQL Server;SERVER=127.0.0.1,52865;DATABASE=master;Trusted_Connection=yes;"
Dim conn_str_accdb
conn_str_accdb = "DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\Users\Public\empty.accdb;"
Dim con
Set con = CreateObject("ADODB.Connection")
con.Open conn_str_accdb
Dim rst
Set rst = CreateObject("ADODB.Recordset")
Dim sql
sql = "SELECT COUNT(*) AS n FROM [ODBC;" + conn_str_sql + "].INFORMATION_SCHEMA.TABLES"
WScript.Echo sql
rst.Open sql, con
WScript.Echo rst(0).Value
rst.Close
con.Close
```

Failing pyodbc code:

```python
import pyodbc
conn_str_sql = r"DRIVER=ODBC Driver 11 for SQL Server;SERVER=127.0.0.1,52865;DATABASE=master;Trusted_Connection=yes;"
conn_str_accdb = r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\Users\Public\empty.accdb;"
conn = pyodbc.connect(conn_str_accdb, autocommit=True)
crsr = conn.cursor()
sql = "SELECT COUNT(*) AS n FROM [ODBC;" + conn_str_sql + "].INFORMATION_SCHEMA.TABLES"
print(sql)
crsr.execute(sql)
print(crsr.fetchval())
crsr.close()
conn.close()
```

The complete ODBC traces are attached. The difference in behaviour appears to be that shortly after SQLExecDirectW is called (line 640 in the vbs trace, line 192 in the Python trace) a call is made to SQLDriverConnectW which is failing under pyodbc.

That call returns SQL_SUCCESS_WITH_INFO for vbs, as shown by the following excerpt starting at line 681 of the vbs trace ...

```none
cscript  odbc_d 15f8-9a8    ENTER SQLDriverConnectW 
        HDBC                0035C6C0
        HWND                00000000
        WCHAR *             0x6E23B274 [      -3] <Invalid string length!>
        SWORD                       -3 
        WCHAR *             0x6E23B274 
        SWORD                       -3 
        SWORD *             0x00000000
        UWORD                        1 <SQL_DRIVER_COMPLETE>

cscript  odbc_d 15f8-9a8    EXIT  SQLDriverConnectW  with return code 1 (SQL_SUCCESS_WITH_INFO)
        HDBC                0035C6C0
        HWND                00000000
        WCHAR *             0x6E23B274 [      -3] <Invalid string length!>
        SWORD                       -3 
        WCHAR *             0x6E23B274 
        SWORD                       -3 
        SWORD *             0x00000000
        UWORD                        1 <SQL_DRIVER_COMPLETE>

        DIAG [IM006] [Microsoft][ODBC Driver Manager] Driver's SQLSetConnectAttr failed (0) 
```

... while the corresponding call from Python returns SQL_ERROR, as we see starting at line 233 of the Python trace:

```none
pythonw.exe -c  1318-1600   ENTER SQLDriverConnectW 
        HDBC                00149388
        HWND                00000000
        WCHAR *             0x6E23B274 [      -3] <Invalid string length!>
        SWORD                       -3 
        WCHAR *             0x6E23B274 
        SWORD                       -3 
        SWORD *             0x00000000
        UWORD                        1 <SQL_DRIVER_COMPLETE>

pythonw.exe -c  1318-1600   EXIT  SQLDriverConnectW  with return code -1 (SQL_ERROR)
        HDBC                00149388
        HWND                00000000
        WCHAR *             0x6E23B274 [      -3] <Invalid string length!>
        SWORD                       -3 
        WCHAR *             0x6E23B274 
        SWORD                       -3 
        SWORD *             0x00000000
        UWORD                        1 <SQL_DRIVER_COMPLETE>

        DIAG [S1110] [Microsoft][ODBC Driver Manager] Only SQL_DRIVER_NOPROMPT is allowed when connection pooling is enabled (0) 
```
[odbc_trace_vbs_success.txt](https://github.com/mkleehammer/pyodbc/files/771163/odbc_trace_vbs_success.txt)
[odbc_trace_py_error.txt](https://github.com/mkleehammer/pyodbc/files/771211/odbc_trace_py_error.txt)

**Comment by mkleehammer** [comment]
I just fixed a bug in which could explain the SQLExecDirectW.  Can you retest with 4.0.6?

**Comment by gordthompson** [comment]
No change with 4.0.6. ODBC trace was the same, right down to the line numbers.

**Comment by gordthompson** [comment]
Additional data point: I knew that the default settings for ODBC Connection Pooling were "off" for the Access ODBC drivers and "on" for the SQL Server ODBC drivers. I switched off connection pooling for "ODBC Driver 11 for SQL Server" in the ODBC Administrator (odbcad32.exe), rebooted the machine, and re-ran the test. The results were the same: the SQLDriverConnectW call still fails with "Only SQL_DRIVER_NOPROMPT is allowed when connection pooling is enabled".

**Comment by gordthompson** [comment]
Solution: The issue can be avoided by adding

```python
pyodbc.pooling = False
```
before calling `pyodbc.connect`.
