### ISSUE TITLE
Segmentation fault with multiple threads using SQL Server

### ISSUE THREAD

**Issue by Jasonca2** [mkleehammer/pyodbc#528]
I'm running into this issue trying to use pyodbc with Django and django-pyodbc-azure. Attempting to make multiple queries against SQL Server with different connections (i.e., multiple api calls to populate a dashboard webpage) results in a segmentation fault. The fault happens at line 307 in django-pyodbc-azure's base.py file. This is the code block for the error:

`conn = Database.connect(connstr,
                                        unicode_results=unicode_results,
                                        timeout=timeout)`

It is importing pyodbc as Database and then invoking the connect method call. The driver that I am using is ODBC Driver 13 for Sql Server, but I have also tried using both 11 and 17 and I still get the same error. I have tested this against both 4.0.25 of pyodbc and 4.0.26

**Comment by mkleehammer** [comment]
Are you using a different query per thread?  Is there a connection pool involved?

What OS and what version of Python?

**Comment by v-chojas** [comment]
Could you provide more information about your environment? What version of Python, which OS, which unixODBC (for Mac/Linux only), etc.

**Comment by Jasonca2** [comment]
I have tried using both python 3.4.5 and python 3.5 on openSUSE 42.1
Latest version of unixODBC (2.3.4 currently)
I have Microsoft's official Linux drivers installed for SQL Server 11, 13 and 17. Trying to run this program against any of them results in a segmentation fault. When running the program locally on my windows machine using SQL Server Native Client 11.0 (and either python 3.4 or 3.5) it does not result in a segmentation fault.

**Comment by v-chojas** [comment]
Please try unixODBC 2.3.7 --- note that 2.3.4 is quite old and _plenty_ of bugs have been fixed since then. See the changelog at http://www.unixodbc.org/

**Comment by Jasonca2** [comment]
I will update unixODBC and see if that resolves this issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mkleehammer** [comment]
Please also make sure you are testing with the recently released 4.0.26.  It turns out there was an important bug fix that could be related.

**Comment by Jasonca2** [comment]
So I update the unixODBC driver to 2.3.7 and pyodbc is also updated to 4.0.26 and I am still getting a segmentation fault. I have attached a file of the output of the segmentation fault using the faulthandler module.
[traceback.txt](https://github.com/mkleehammer/pyodbc/files/2905999/traceback.txt)

**Comment by v-chojas** [comment]
Can you post an [ODBC trace](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/data-access-tracing-with-the-odbc-driver-on-linux) ?

**Comment by Jasonca2** [comment]
Now I am no longer getting a segmentation fault. The program just hangs after the second database query is run.

**Comment by Jasonca2** [comment]
Turns out it is an issue with Microsoft's support for the distribution I am using. They don't support openSuSe Leap 42.1 for their linux drivers.

**Comment by v-chojas** [comment]
There should not be a problem with open or closed SuSE, I believe openSuSE 42 is equivalent to SuSE 12.

**Comment by David-Engel** [comment]
@Jasonca2 While openSuSe is not officially supported, it might just be something wrong with your configuration which would also manifest under SuSE 12. I wouldn't give up just because there isn't an ODBC driver package specific to openSuSe.
